### ISSUE TITLE
Instance variables

### ISSUE THREAD

**Issue by mvid** [echeran/kalai#11]
Not really an issue, but more looking for an example or guidance on how to reference instance variables in methods on classes? Using `this.valueToAccess` in Java, for instance

**Comment by mvid** [comment]
In that same theme, are there examples for constructors?

**Comment by mvid** [comment]
Yes, that makes sense. I would love to help more on this project, but can't find a way to contact you.

**Comment by echeran** [comment]
We're on the Clojurians slack in the `#kalai` channel, that's the best way, right now.  I thought I added that info on the Readme, but not yet, I guess.  Or an email to me works (should be in the commit messages).
